### ISSUE TITLE
Thermal Shield leak ?

### ISSUE THREAD

**Issue by OzoneGrif** [KSP-RO/TestFlight#89] opened 2015-09-19 00:13 UTC
The shield was apparently considered like a tank, and it leaked its ablator...
I can understand that kind of behaviour while burning on a reentry, but in space ?

**Comment by jwvanderbeck** [comment] 2015-11-14 20:53
Since ablator is just a tank resource, no doub lt the configs are grabbing it when it shouldn't.

**Comment by jwvanderbeck** [comment] 2016-03-03 18:08
I'm goign to close this bug - it is valid but will be taken care of as config improve.  In other words it isn't so much a bug in TF as just a limitation of the configs.

**Closed by jwvanderbeck** 2016-03-03 18:08 UTC
Labels: bug

**Comment by Starstrider42** [comment] 2016-05-25 08:35
So where should we report config bugs? I came across this while preparing to report a related issue (that heat shields, ore bins, etc. are apparently capable of spontaneously exploding).

**Comment by jwvanderbeck** [comment] 2016-05-25 14:41
The problem is I don't really do configs.  The configs for Realism Overhaul are managed by them.  The configs for stock were put together by someone a long time ago during development of TestFlight and really haven't been touched yet, except when I ported them to the new system.  I don't play stock, and i'm not very good at configs, so on the stock side its a bit of a mess.  I keep hoping someone will step up and maintain a config pack for stock.

**Comment by Starstrider42** [comment] 2016-05-25 15:13
Fair enough. I can't commit to maintaining a config pack yet, but I'll keep it in mind.
